SELECT TOP 10 * FROM NAME

SELECT TOP 10 * FROM TITLE_AKAS

SELECT TOP 10 * FROM TITLE_BASICS

SELECT TOP 10 * FROM TITLE_CREW

SELECT TOP 10 * FROM TITLE_EPISODE

SELECT TOP 10 * FROM TITLE_PRINCIPALS

SELECT TOP 10 * FROM TITLE_RATINGS